// Copyright (C) 2017 - IIT Bombay - FOSSEE
//
// This file must be used under the terms of the CeCILL.
// This source file is licensed as described in the file COPYING, which
// you should have received as part of this distribution.  The terms
// are also available at
// http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt
// Organization: FOSSEE, IIT Bombay
// Email: toolbox@scilab.in

function AVRPWM0SetDuty(duty)
<<<<<<< HEAD
//Function to Set Duty cycle of PWM Output generated by Timer0 at OC0 pin. 
//   
//Parameters
//	duty : It holds an integer value from 0 to 100 which sets the percentage of time for which signal is active.
//
//Description
//      Each Micro controller has PWM output pins which can generate varying voltage
//      from 0V-5V.In this function by varying the duty cycle, varying voltage can be produced.
// 
//      This is curretly dummy function. It provides no functionality but is required for providing support for generating C code for AVR.
//
//Examples
=======
//Function to Set Duty cycle of PWM Output generated by Timer0 at OC0 pin.    
//Parameters
//	duty : It holds an integer value from 0 to 100 which sets the percentage
//             of time for which signal is active.
//Description
//      Each Micro controller has PWM output pins which can generate varying voltage
//      from 0V-5V.In this function by varying the duty cycle, varying voltage can be 
//      produced.
//Example
>>>>>>> 9e5793a7b05b23e6044a6d7a9ddd5db39ba375f0
//      AVRPWM0SetDuty(50); //Produces 2.5V at OC0 pin
//      AVRPWM0SetDuty(0); //Produces 0V at OC0 pin
//See also
//     AVRPWM0Setup
//
//Authors
//     Ashish Kamble
//
<<<<<<< HEAD
=======
// This is curretly dummy function. It provides no functionality but is required 
// for providing support for generating C code for AVR.
>>>>>>> 9e5793a7b05b23e6044a6d7a9ddd5db39ba375f0

if(duty>100) then 
disp("Error : Invalid input argument ''duty'' in AVRPWM0SetDuty function.");
end
endfunction
