/* Copyright (C) 2016 - IIT Bombay - FOSSEE

 This file must be used under the terms of the CeCILL.
 This source file is licensed as described in the file COPYING, which
 you should have received as part of this distribution.  The terms
 are also available at
 http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt
 Author: Ashish Kamble
 Organization: FOSSEE, IIT Bombay
 Email: toolbox@scilab.in
*/ 
//Function to Set Duty cycle and Top Value of PWM Output generated by Timer1 at OC1A or OC1B pin.

#include "AVRPeripheralPWM.h"

uint8 u8AVRPWM1SetDutys(uint8 output_pin, uint16 duty, uint16 Top_Value)
{
 uint16 duty_value = 0;
 ICR1 = Top_Value;
 if(output_pin==0)
 {
 duty_value = (((uint16)(duty * Top_Value))/100);
 OCR1A = duty_value;
 } 
 else if(output_pin==1)
      {
       duty_value = (((uint16)(duty * Top_Value))/100);
       OCR1B = duty_value;
      }    
 return 0;
}
