# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr
BOARD_TAG    = uno
USER_LIB_PATH = ../../
ARDUINO_LIBS = src/c includes interfaces ../Temp
ARDUINO_PORT = /dev/ttyACM0
include /usr/share/arduino/Arduino.mk
