#define SCI2Cint int
#include "SCI2CMacroInterface.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "constant.h"
#include "notFound.h"
#include "doubleComplex.h"
#include "length.h"
#include "int_length.h"
#include "min.h"
#include "max.h"
#include "floatComplex.h"
#include "RealToComplex.h"
#include "conj.h"
#include "cos.h"
#include "ones.h"
#include "zeros.h"
#include "OpApex.h"
#include "OpColon.h"
#include "OpDotSlash.h"
#include "OpDotHat.h"
#include "OpEqual.h"
#include "OpPlus.h"
#include "OpMinus.h"
#include "OpStar.h"
#include "OpIns.h"
#include "OpExt.h"
#include "sin.h"
#include "FileManagement.h"
#include "OpLogGt.h"
#include "OpLogLt.h"
#include "OpLogGe.h"
#include "OpLogLe.h"
#include "OpLogEq.h"
#include "OpLogOr.h"
#include "OpLogAnd.h"
#include "ConvertPrecision.h"
#include "SCI2Cfft.h"
#include "SCI2Cconvol.h"
#include "sqrt.h"
#include "int_sqrt.h"
#include "abs.h"
#include "int_abs.h"
#include "exp.h"
#include "int_exp.h"
#include "log1p.h"
#include "log.h"
#include "int_log.h"
#include "log10.h"
#include "int_log10.h"
#include "sum.h"
#include "int_sum.h"
#include "mean.h"
#include "int_mean.h"
#include "pythag.h"
/* interfacing find */
#include "find.h"
#include "int_find.h"
/* interfacing cat */
#include "cat.h"
#include "int_OpRc.h"
#include "int_OpCc.h"
/* interfacing disp */
#include "disp.h"
#include "int_disp.h"/* interfacing multiplication */
#include "multiplication.h"
#include "int_OpStar.h"
#include "int_OpDotStar.h"
/* interfacing addition */
#include "addition.h"
#include "int_OpPlus.h"/* interfacing subtraction */
#include "subtraction.h"
#include "int_OpMinus.h"
/* interfacing fill */
#include "fill.h"/* interfacing ones */
#include "ones.h"
